# Generated by Django 4.1.3 on 2022-11-21 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='wordtopdfmodel',
            name='pdfFile',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
