# Generated by Django 4.1.3 on 2022-11-28 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_convertermodel_imageconvertermodel_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imageconvertermodel',
            name='image',
        ),
    ]
