# Generated by Django 4.1.3 on 2022-11-29 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_imageconvertermodel_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='imageconvertermodel',
            name='convertedFromExtension',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
