# Generated by Django 4.1.3 on 2022-12-01 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_imageconvertermodel_convertedfromextension'),
    ]

    operations = [
        migrations.CreateModel(
            name='PdfToImageModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('folderName', models.TextField(blank=True, default='', null=True)),
                ('Image1', models.TextField(blank=True, default='', null=True)),
                ('Image2', models.TextField(blank=True, default='', null=True)),
                ('Image3', models.TextField(blank=True, default='', null=True)),
                ('Image4', models.TextField(blank=True, default='', null=True)),
                ('Image5', models.TextField(blank=True, default='', null=True)),
            ],
        ),
    ]
