# Generated by Django 4.1.3 on 2022-12-01 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_pdftoimagemodel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pdftoimagemodel',
            old_name='Image1',
            new_name='Image',
        ),
        migrations.RemoveField(
            model_name='pdftoimagemodel',
            name='Image2',
        ),
        migrations.RemoveField(
            model_name='pdftoimagemodel',
            name='Image3',
        ),
        migrations.RemoveField(
            model_name='pdftoimagemodel',
            name='Image4',
        ),
        migrations.RemoveField(
            model_name='pdftoimagemodel',
            name='Image5',
        ),
    ]
