# Generated by Django 4.1.3 on 2022-12-04 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_rename_image1_pdftoimagemodel_image_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImagesToPdf',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pdfName', models.TextField(blank=True, default='', null=True)),
            ],
        ),
    ]
